import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "WASP",
  description: "Generated by create next app",
};
const myFont = localFont({
  src: [
    {
      path: "../public/fonts/Satoshi-Black.eot",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi-Black.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/Satoshi-Bold.eot",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi-Bold.eot",
      weight: "700",
      style: "italic",
    },
  ],
});
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={myFont.className}>
      <body>{children}</body>
    </html>
  );
}
